# The Site Configuration

# Import the theme
remote_theme: cotes2020/jekyll-theme-chirpy

title: Chirpy                          # the main title

tagline: A text-focused Jekyll theme   # it will display as the sub-title

description: >-                        # used by seo meta and the atom feed
  A minimal, portfolio, sidebar,
  bootstrap Jekyll theme with responsive web design
  and focuses on text presentation.